name: CD
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish?'
        required: false
        default: 'false'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1 # we need to be very specific here due to https://github.com/nodejs/node/issues/52240
      - shell: pwsh
        run: |
          if ($IsLinux) {
            python3 -m pip install setuptools
          }
          elseif ($IsMacOS) {
            brew install python-setuptools
          }
          elseif ($IsWindows) {
            python3 -m pip install setuptools
          }
      - run: npm i -g node-gyp
      - run: npm install
        env:
          npm_config_arch: ${{ matrix.arch }}
      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
      - run: npx vsce package --target ${{ env.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.target }}
          path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs && (github.event.inputs.publish == 'true')
    steps:
      - uses: actions/download-artifact@v4
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
